---
  - name: login to GitHub remote registry using your account
    docker_login:
      username: "{{ github_registry_username }}"
      password: "{{ github_registry_authkey }}"
      registry: ghcr.io

  - name: Inlcude manager init task
    include_tasks: ./init.manager.yml
    when: node_type == 'manager'

  - name: Inlcude node init task
    include_tasks: ./init.node.yml
    when: node_type == 'node'

  - name: Replace node labels with new labels
    docker_node:
      hostname: "{{ item.node }}"
      labels: "{{ item.labels }}"
      labels_state: "replace"
    loop: "{{ node_labels }}"
    when: node_type == 'manager'

  - name: Create docker network for monitoring
    docker_network:
      name: monitoring-public
      driver: overlay