---
- name: Get join-token for worker nodes
  set_fact:
    join_token_worker: "{{ hostvars[groups['managers'][0]].result.swarm_facts.JoinTokens.Worker }}"

- name: Join workers
  community.general.docker_swarm:
    state: join
    join_token: "{{ join_token_worker }}"
    advertise_addr: "{{ ansible_host }}"
    remote_addrs: "{{ swarm_remote_addr }}"
  when:
    - inventory_hostname not in groups['managers']