---
  - include_tasks: './init.yml'

  - include_tasks: './_traefik.yml'
    when: node_type == 'manager'

  - include_tasks: './portrainer.yml'
    when: node_type == 'manager' and portainer_enabled == true

  - include_tasks: './_prometheus.yml'
    when: node_type == 'manager' and prometheus_enabled == true

  - include_tasks: './_grafana.yml'
    when: node_type == 'manager' and grafana_enabled == true

  - include_tasks: './_node_exporter.yml'
    when: node_type == 'manager' and node_exporter_enabled == true

  - include_tasks: './homer.yml'
    when: node_type == 'manager' and homer_enabled == true