---
- name: 'Install neofetch'
  include_role:
    name: 'tmiller02.neofetch'

- name: Ensure neofetch is loaded with bash
  ansible.builtin.lineinfile:
    path: "/home/{{ sysadmins.diffy0712.sysadmin_user }}/.bashrc"
    regexp: '^neofetch'
    line: neofetch
    owner: "{{ sysadmins.diffy0712.sysadmin_user }}"
    group: "{{ sysadmins.diffy0712.sysadmin_user }}"
    mode: '0644'

- name: "Set a hostname to {{ inventory_hostname }}"
  hostname:
    name: "{{ inventory_hostname }}"
