---
- name: Add node hosts to /etc/hosts file                                                    
  lineinfile:                                                                       
    path: /etc/hosts                                                          
    line: "{{ item }}"                                                              
  loop: "{{ node_hosts }}"