---
  - name: 'Set timezone'
    include_tasks: ./timezone.yml

  - name: 'Manage /etc/hosts'
    include_tasks: ./hosts.yml

  - name: 'Manage users'
    include_tasks: ./users.yml

  - name: 'Set message of the day and login banner'
    include_tasks: ./login.yml

  - name: 'Install all required packages'
    include_tasks: ./packages.yml

  ## https://github.com/geerlingguy/ansible-role-pip/issues/57#issuecomment-2108657898
  - name: 'Fix python'
    include_tasks: ./python_fix.yml

  - name: 'Secure ssh'
    include_tasks: ./ssh.yml

  ##- name: 'Configure firewall'
  ##  include_tasks: ./firewall.yml

  - name: 'Install and configure docker'
    include_tasks: ./docker.yml

  - name: 'Sez up cli for users'
    include_tasks: ./cli.yml